### PR TITLE
added mandatory and must support for name, birthDate, identifier and …

### PR DESCRIPTION
**Pull request by riksmithies**
…set profile itself to be active

now derives from UKCore-Patient - this may break the CI build if it cannot access the snapshots in the UK Core package

### CODE REVIEW

**Comment by Dunmail** [comment]
What do we need to do after this change in order to make the build work, both locally and via CI?

**Comment by KevinMayfield** [comment]
Q. Is you scope API interactions only or does it include additional profiles. 

Just conscious some points raised above align with profiling in NHS Wales and England.  

E.g. https://simplifier.net/guide/NHSDigital/Home/FHIRAssets/AllAssets/Profiles/NHSDigital-Patient.guide.md?version=current
and 
https://simplifier.net/guide/FHIR-Standards-Wales-Implementation-Guide/Home/FHIR-Assets/Profiles-and-Extensions/Profiles/DataStandardsWales-Patient.page.md?version=current

**Comment by riksmithies** [comment]
@Dunmail also see an mail I sent about CI build. 

To fix locally:

When using UK Core in a derived profile you may get:
Sushi: error Structure Definition https://fhir.hl7.org.uk/StructureDefinition/UKCore-Patient is missing a snapshot. Snapshot is required for import.

There is a fix here but it turned out to be incorrect (because "bake" command has become "inflate", see below for correct one):
https://fshschool.org/docs/sushi/running/#structure-definition-is-missing-snapshot-error

It needs firely-terminal, read here:
https://simplifier.net/downloads/firely-terminal
at a command prompt:
dotnet tool install -g firely.terminal

you will need to log in to the command "fhir" - which is firely.terminal using a Simplfier user/password

You can do:
fhir versions fhir.r4.ukcore.stu1
to see what you have

or this:
fhir cache

Then do:
>fhir inflate --package fhir.r4.ukcore.stu1

I got a lot of "Expansion was skipped, because: ConceptSets with a filter are not yet supported."
But the resources did seem to get snapshots, and FSH works after that.

On Windows your packages are physically in C:\Users\{your user name}\.fhir\packages
You can look before and after and see that the snapshots do get added in the JSON files.

Or contact me and I can send the updated JSON for UK core patient and it can be placed into the package cache, presumably.

**Comment by riksmithies** [comment]
@KevinMayfield thanks
https://fhir.nhs.uk/StructureDefinition/NHSDigital-Patient has one differential and that is to add mandatory DoB. Which is ok but it in turn derives from https://fhir.nhs.uk/StructureDefinition/NHSDigital-Patient which constrains a lot of other things.
I don't think it will be practical for every profile created to derive from every other similar profile. We want to DRY but there are limits the the granularity that is practical. 
Interesting that NHSDigital-Patient has made things Must Support but not 1..X e.g. date of birth and name. So it is catering for patients who cannot yet be identified.

**Comment by KevinMayfield** [comment]
I wouldn't be too fussed on the detail, just that NHS England has profiles (I missed off you said MUST support).

**Pull request merged**
